// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEyzD9qlqV_qUuRJKajpFVqMW-BaL4Wgs',
    appId: '1:674829039138:web:f1cab3e574a31009707c7b',
    messagingSenderId: '674829039138',
    projectId: 'chatappflutter-4c4ce',
    authDomain: 'chatappflutter-4c4ce.firebaseapp.com',
    storageBucket: 'chatappflutter-4c4ce.firebasestorage.app',
    measurementId: 'G-6S35K0HE5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAd7RaWtM-yrCAIb-CoCJptCkbphLUTrU',
    appId: '1:674829039138:android:5a3f63ced7b0f24a707c7b',
    messagingSenderId: '674829039138',
    projectId: 'chatappflutter-4c4ce',
    storageBucket: 'chatappflutter-4c4ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3eLyejg9TFeBhWHH3xLly9hZgTduc0W0',
    appId: '1:674829039138:ios:215e47ac1999525b707c7b',
    messagingSenderId: '674829039138',
    projectId: 'chatappflutter-4c4ce',
    storageBucket: 'chatappflutter-4c4ce.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3eLyejg9TFeBhWHH3xLly9hZgTduc0W0',
    appId: '1:674829039138:ios:215e47ac1999525b707c7b',
    messagingSenderId: '674829039138',
    projectId: 'chatappflutter-4c4ce',
    storageBucket: 'chatappflutter-4c4ce.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEyzD9qlqV_qUuRJKajpFVqMW-BaL4Wgs',
    appId: '1:674829039138:web:e13cb35cb8cb8492707c7b',
    messagingSenderId: '674829039138',
    projectId: 'chatappflutter-4c4ce',
    authDomain: 'chatappflutter-4c4ce.firebaseapp.com',
    storageBucket: 'chatappflutter-4c4ce.firebasestorage.app',
    measurementId: 'G-E99YLE64MT',
  );

}